### ISSUE TITLE
Attribute Types Differ from Current Column Types

### ISSUE THREAD

**Issue by dunnnw** [MscrmTools/MsCrmTools.MetadataDocumentGenerator#18]
The Attribute Types that are used when the Metadata Document Generator runs are currently different than the ones Dynamics uses. It would be helpful to include documentation on what those mappings are if possible.

---
- Deployment: Online
- DB Version: 9.2.21064.148
- Connection Controls Version: 1.2021.6.44
- XrmToolBox Version: 1.2021.6.51
- Tool Version: 1.2021.4.4

**Comment by eccountable** [comment]
Don't waste time documenting a mapping between the old and new nomenclature of data types. Either make an option to choose 'classic' or 'UI' or just move on and join the rest of the world and use the attribute types defined in the documentation. The problem is that when I tell my clients to use this tool and they see "Picklist" instead of "Choice" then it causes confusion.
